### PR TITLE
Drf style sorting

### PR DESCRIPTION
**Pull request by iamanikeev**

### CODE REVIEW

**Comment by iamanikeev** [comment]
Build is passing now. Please let me know if I miss something.

**Comment by MattBroach** [comment]
This is awesome @iamanikeev, thanks for putting this together!  The ability to sort by related objects is particularly nice.  I bet it would be possible to create a recursive version of the sort function that could handle more than one related lookup, but we can flag that for future iterations.

I do have a few small suggestions before this gets merged:

1. I think you should move the code that's in `initial` into a function on the mixin, something like `get_sorting_field`, and just call that function in `initial`.  It's possible that someone would want to use the new sort functionality on the `FlatMultipleModelAPIViewset` rather than just the view, so we'd need to also call the function there, and ideally we'd do it with minimal code duplication.  Incidentally, I'm not 100% convinced the code needs to live in `initial` at all -- there's nothing about it that needs to run before it's passed to the `get` handler (unlike, say, authentication), it just needs to get called before the sort function -- but I'm not particularly dogmatic about that point.  But I DO think the bulk of the code should live in the mixin.

2. Super minor point, but I would change the name of the function `get_datum_field` to `sort_by` or something like that: I think it'll make things a little more readable for people browsing the code

3. Not at all minor point: add yourself to `contributors.rst`!  You put a lot of good work into this, and it should be acknowledged.

Let me know if you have any questions.  Once this changes are made, this will be good to merge.

**Comment by iamanikeev** [comment]
Thanks for the feedback! I'll add the changes you mentioned tomorrow. Also will increase code coverage a bit (it's been decreased by this PR)

**Comment by iamanikeev** [comment]
@MattBroach all 3 items done:) Also I have changed behavior a bit: it now fails in case if path contains a list, instead of sorting by the list's first item, it seems more reasonable to me, because otherwise it'd be kinda ambiguous.

**Comment by MattBroach** [comment]
Sorry for the delay!  Thanks for all the fixes, this is great.

**Pull request merged**
