### PR TITLE
Support sorting by several fields

### PR DESCRIPTION
**Pull request by iamanikeev**
Hi! Please check that out. I have a bad feeling about the ascending\descending order though. I chose to pick the sorting direction from the first sort field only, but this looks kinda like half-done thing. On the other hand, passing more complex key function to `sorted()`, or using `list.sort()` might affect the performance for large amount of data. What do you think about this problem?

### CODE REVIEW

**Comment by MattBroach** [comment]
Hey @iamanikeev, thanks again for putting this together.  I think the idea of being able to sort on multiple keys is great, but I think we can probably smooth out the interface/API a little bit.

In particular, I don't love the idea of a comma-separated single string for the `sort_field`-- the comma-separated strings are necessary for query params (because we don't have any other options there), but when using them on a field on a class it just doesn't feel very Django-like to me.  I think we can use the way Django handles [ordering on models](https://docs.djangoproject.com/en/2.0/ref/models/options/#ordering) as a baseline: it's a list of tuple or strings, each of which can have a reverse`-` in front of them.  

Tell me what you think about this as a solution:

1) We allow users to set the `sorting_fields` directly.  This would be a list/tuple of strings, just like on the `ordering` Meta property above.  We should actually update the documentation to reflect this, and let that be the preferred way of setting the sort directly on the class (so, even if you only wanted to sort by one field, you'd write `sorting_fields = ['my_field']` on the View/Viewset).
2) To not break backwards compatibility, we keep the single `sort_field` there, but remove mention from it in the docs.  In the `prepare_sorting_fields` function (or some other place), if the `sort_field` has a value then you can just set `sorting_fields = [sort_field]`.  This is only done to make sure we don't break people's current code -- and, to be super nice about it, maybe we can add a deprecation notice to the code.
3) I think we should probably get it working so that someone could, in fact, combine both ascending and descending sorts, just like they can do both ascending and descending orderings on the Model (for example, `sorting_fields = ['field_1', '-field_2', 'field_3']`).  This [SO answer](https://stackoverflow.com/questions/6666748/python-sort-list-of-lists-ascending-and-then-decending?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) gives one possible method on how to do that, but I'm open to other implementations (do NOT use the accepted answer on that SO page, though, because that is not generic and would not work on strings or other non-number data types).  Honestly, I wouldn't worry too much about performance here: if someone is requesting data that is so lengthy that multiple sorting passes would be a huge performance cost, they should probably be paginating anyway.

Does that make sense?  If so, does it strike you as a good solution?

**Comment by iamanikeev** [comment]
Hi @MattBroach, thanks for the feedback! You are talking about passing `cmp` function to sorted, as a possible solution? I've seen that, and had doubts about it, because it's been stated that it may be slow for relatively big data sets. But you're probably right that this should not be the case here. I'll give it a try. About `sorting_field` property - also agreed, will change that. I'll try to commit fixes during this week.

**Comment by MattBroach** [comment]
Actually, I'm suggesting an even more naive solution: simply calling `sort` once for each element of `sorting_fields` -- I think a custom `cmp` function would be hard to do with a mix of ascending and descending sorts (especially if the data is anything other than ints or floats).  I think that a clean (and consistent with the rest of Django) interface is WAY more important than raw performance in this case -- and if someone has needs for some particularly efficient sort on huge data sets, they can always overwrite the `sort_by` on their View/Viewset classes tailor the sorting specifically to their needs.

**Comment by iamanikeev** [comment]
Done. I didn't test deprecation warning yet, will check it on my project soon (like this evening or tomorrow).

**Comment by iamanikeev** [comment]
I've found `DeprecationWarning` kinda useless, since it's being suppressed by default [since Python 2.7](https://docs.python.org/3.5/whatsnew/2.7.html#changes-to-the-handling-of-deprecation-warnings). So if we add it, it is not guaranteed that everyone sees the warning. On the other hand, this is exactly a deprecation warning, so using of some other type of warning doesn't seem right. Anyway, I suggest leaving it there, it still might be noticed by some people.

**Comment by iamanikeev** [comment]
Hey @MattBroach! Did you have any chance to look at this once more?

**Comment by MattBroach** [comment]
Hey @iamanikeev, so sorry for the delay -- I've been traveling a bunch this month, so I have not yet had a chance to look this over.  I should be able to get to it in the next couple days -- thank you for your patience!

**Pull request merged**
